const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: 'image/ci1.jpg',
        cat: 'cipla',
        des:'hi',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '96',
        image: 'image/ci5.jpg',
        cat: 'cipla',
        des:'hi1',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '236',
        image: 'image/ci2.jpg',
        cat: 'cipla',
        des:'hi2',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '636',
        image: 'image/ci4.jpg',
        cat: 'cipla',
        des:'hi3',
        type: 'new',
    },
    {
        id: 5,
        Name: 'product5',
        price: '98',
        image: 'image/mk1.jpg',
        cat: 'mankind',
        des:'hi4',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '59',
        image: 'image/mk3.jpg',
        cat: 'mankind',
        des:'hi5',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/mk6.jpg',
        cat: 'mankind',
        des:'hi6',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/mk5.jpg',
        cat: 'mankind',
        des:'hi7',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '67',
        image: 'image/o1.jpg',
        cat: 'orimis',
        des:'hi8',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '76',
        image: 'image/o2.jpg',
        cat: 'orimis',
        des:'hi9',
        type: 'top',
    },
    {
        id: 11,
        Name: 'product11',
        price: '87',
        image: 'image/o3.jpg',
        cat: 'orimis',
        des:'hi10',
        type: 'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: '807',
        image: 'image/o4.jpg',
        cat: 'orimis',
        des:'hi11',
        type: 'top',
    },
]
export default Homeproduct;